# Generated by Django 4.0.4 on 2023-04-12 00:01

import PTitulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0002_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[PTitulo.models.validate_chilean_rut], verbose_name='Rut'),
        ),
    ]
