# Generated by Django 4.0.4 on 2023-04-12 00:08

import PTitulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0003_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=20, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=20, validators=[PTitulo.models.validate_password_complexity], verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(help_text='Ingrese rut sin puntos ni guiones', max_length=9, primary_key=True, serialize=False, validators=[PTitulo.models.validate_chilean_rut], verbose_name='Rut'),
        ),
    ]
