# Generated by Django 4.1.7 on 2023-04-27 15:04

import PTitulo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0004_alter_usuario_apellido_alter_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(help_text='Ingrese rut sin puntos ni guiones', max_length=9, primary_key=True, serialize=False, validators=[PTitulo.models.validate_chilean_rut, PTitulo.models.validate_alphanumeric], verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre')),
                ('foto_1', models.CharField(max_length=100, verbose_name='Foto 1')),
                ('foto_2', models.CharField(max_length=100, verbose_name='Foto 2')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.usuario', verbose_name='Dueño')),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.tipomascota', verbose_name='Tipo de Mascota')),
            ],
        ),
    ]
