# Generated by Django 4.1.7 on 2023-04-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0005_tipomascota_alter_usuario_rut_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_2',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.tipomascota', verbose_name='Tipo de Mascota'),
        ),
    ]
