# Generated by Django 4.1.7 on 2023-04-28 00:31

import PTitulo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0006_alter_mascota_foto_2_alter_mascota_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('radio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Radio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.CharField(max_length=250, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='¿Borrado?')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.estado', verbose_name='Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.mascota', verbose_name='Mascota')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.tipoanuncio', verbose_name='Categoría')),
            ],
        ),
    ]
