# Generated by Django 4.1.7 on 2023-04-28 00:36

import PTitulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0007_estado_posicion_tipoanuncio_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipoanuncio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipomascota',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[PTitulo.models.validate_min, PTitulo.models.validate_only_letters], verbose_name='Nombre'),
        ),
    ]
