# Generated by Django 4.1.7 on 2023-04-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0010_alter_estado_nombre_alter_tipomascota_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='anuncio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PTitulo.anuncio', verbose_name='Anuncio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.mascota', verbose_name='Mascota'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Admin')),
                ('isClosed', models.BooleanField(default=False, verbose_name='¿Cerrado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='PTitulo.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
