# Generated by Django 4.1.7 on 2023-04-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0011_posicion_anuncio_alter_anuncio_mascota_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_admin', to='PTitulo.usuario', verbose_name='Admin'),
        ),
    ]
