# Generated by Django 4.1.7 on 2023-04-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0012_alter_reporte_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='respuesta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Respuesta'),
        ),
    ]
