# Generated by Django 4.1.7 on 2023-06-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0018_rename_descripción_anuncio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='msgToken',
            field=models.CharField(default=1, max_length=256, verbose_name='Mensaje Token'),
            preserve_default=False,
        ),
    ]
