# Generated by Django 4.1.7 on 2023-06-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0019_usuario_msgtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='msgToken',
            field=models.CharField(max_length=256, unique=True, verbose_name='Mensaje Token'),
        ),
    ]
