# Generated by Django 4.1.7 on 2023-06-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0024_remove_reputacion_comentario_reputacion_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTitulo.usuario'),
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputaciones_emitidas', to='PTitulo.usuario'),
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputaciones_recibidas', to='PTitulo.usuario'),
        ),
    ]
