# Generated by Django 4.1.7 on 2023-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0025_alter_recompensa_usuario_alter_reputacion_evaluador_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reputacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
