# Generated by Django 4.1.7 on 2023-06-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0026_alter_reputacion_unique_together_alter_reputacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reputacion',
            name='promedio',
        ),
    ]
