# Generated by Django 4.1.7 on 2023-06-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0027_remove_reputacion_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputacion',
            name='promedio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='reputacion',
            unique_together={('usuario', 'evaluador')},
        ),
    ]
