# Generated by Django 4.1.7 on 2023-06-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTitulo', '0028_reputacion_promedio_alter_reputacion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reputacion',
            name='promedio',
        ),
    ]
